CollectiDex/CollectiDex/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as users_views

urlpatterns = [
    path('', users_views.index, name='index'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('cards/', include('cards.urls')),
    path('sets/', include('sets.urls')),
    path('portfolio/', include('portfolio.urls')),
]

CollectiDex/portfolio/urls.py
from django.urls import path
from . import views

app_name = 'portfolio'
urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('collection_cards/', views.cards_in_collection, name='collection_cards'),
    path('collection_sets/', views.sets_in_collection, name='collection_sets'),
    path('type/<str:card_type>/', views.cards_by_type, name='cards_by_type'),  # Cards per type
    path('rarity/<str:rarity>/', views.cards_by_rarity, name='cards_by_rarity'),  # Cards per rarity
]

CollectiDex/sets/urls.py
from django.urls import path
from . import views

app_name = 'sets'

urlpatterns = [
    path('', views.set_list, name='set_list'),  # Displays all sets by default
    path('search/', views.search_sets, name='search_sets'),  # Search sets based on filters
    path('view/<str:set_id>/', views.set_view, name='set_view'),
]

CollectiDex/portfolio/models.py
from django.db import models

# Create your models here.

CollectiDex/portfolio/views.py
from django.shortcuts import render
from cards.models import UserCard
from sets.models import UserSet
from pokemontcgsdk import Card
from django.contrib.auth.decorators import login_required
from django.core.cache import cache
from django.core.paginator import Paginator
from django.db.models import Sum, Count, F

def get_market_price(card_id, variant_type):
    # Define a cache key for the card and variant type
    cache_key = f"card_{card_id}_variant_{variant_type}_price"

    # Try to get the price from the cache
    cached_price = cache.get(cache_key)
    if cached_price:
        return cached_price  # If cached, return the cached price

    # If not in cache, fetch the price from the API
    try:
        card_info = Card.find(card_id)
        if not card_info or not hasattr(card_info, 'tcgplayer') or not card_info.tcgplayer.prices:
            return 0  # If no data, return 0

        price_info = getattr(card_info.tcgplayer.prices, variant_type, None)
        market_price = price_info.market if price_info else 0

        # Cache the price for future requests, with a shorter expiry time (e.g., 15 minutes)
        cache.set(cache_key, market_price, timeout=45 * 60)  # Cache for 15 minutes

        return market_price
    except Exception as e:
        print(f"Error fetching market price: {e}")
        return 0  # Return 0 in case of an error

@login_required(login_url='users:landing')
def cards_by_type(request, card_type):
    # Fetch the user's cards from the UserCard model
    user_cards = UserCard.objects.filter(user=request.user, card__supertype=card_type)

    # Set up pagination for the filtered cards
    paginator = Paginator(user_cards, 10)  # Show 10 cards per page
    page_number = request.GET.get('page', 1)
    page_obj = paginator.get_page(page_number)

    return render(request, 'portfolio/cards_by_type.html', {
        'page_obj': page_obj,
        'card_type': card_type
    })

# Cards by rarity view
@login_required(login_url='users:landing')
def cards_by_rarity(request, rarity):
    # Fetch the user's cards from the UserCard model
    user_cards = UserCard.objects.filter(user=request.user, card__rarity=rarity)

    # Set up pagination for the filtered cards
    paginator = Paginator(user_cards, 10)  # Show 10 cards per page
    page_number = request.GET.get('page', 1)
    page_obj = paginator.get_page(page_number)

    return render(request, 'portfolio/cards_by_rarity.html', {
        'page_obj': page_obj,
        'rarity': rarity
    })

@login_required(login_url='users:landing')
def cards_in_collection(request):
    user_cards = UserCard.objects.filter(user=request.user)
    paginator = Paginator(user_cards, 10)
    page_number = request.GET.get('page', 1)
    page_obj = paginator.get_page(page_number)

    return render(request, 'portfolio/total_cards_in_collection.html', {'page_obj': page_obj})

@login_required(login_url='users:landing')
def sets_in_collection(request):
    user_sets = UserSet.objects.filter(cards__usercard__user=request.user).distinct()

    sets_with_progress = []

    # Calculate progress for each set
    for user_set in user_sets:
        total_cards_in_set = user_set.total  # Assuming `total` is the total number of cards in the set
        user_cards_in_set = user_set.cards.filter(usercard__user=request.user).count()  # Count how many cards the user has in the set

        # Calculate the completion percentage
        if total_cards_in_set > 0:
            completion_percentage = (user_cards_in_set / total_cards_in_set) * 100
        else:
            completion_percentage = 0

        # Add the calculated completion percentage to the context for use in the template

        sets_with_progress.append({
            'user_set': user_set,
            'user_cards_in_set': user_cards_in_set,
            'completion_percentage': completion_percentage
        })

    paginator = Paginator(sets_with_progress, 10)
    page_number = request.GET.get('page', 1)
    page_obj = paginator.get_page(page_number)

    return render(request, 'portfolio/total_sets_in_collection.html', {'page_obj': page_obj})

@login_required(login_url='users:landing')
def dashboard(request):
    user = request.user

    # Fetch user sets and cards
    user_cards = UserCard.objects.filter(user=user).select_related('card')  # Optimized query for UserCard data

    # Count the number of completed sets based on the is_completed field
    completed_sets = UserSet.objects.filter(is_completed=True).count()

    type_totals = (
        user_cards.values('card__supertype')
        .annotate(total=Sum('quantity'))
        .order_by('card__supertype')
    )

    rarity_totals = (
        user_cards.values('card__rarity')
        .annotate(total=Sum('quantity'))
        .order_by('card__rarity')
    )

    # Calculate statistics
    total_cards = sum(card.quantity for card in user_cards)
    total_value = 0

    for user_card in user_cards:
        card = user_card.card
        variant_type = user_card.variant_type

        market_price = get_market_price(card.card_id, variant_type) or 0
        total_value += market_price * user_card.quantity

    unique_cards = user_cards.values('card__card_id', 'variant_type').distinct().count()

    # Render the dashboard with stats and completed sets
    return render(request, 'portfolio/dashboard.html', {
        'total_cards': total_cards,
        'total_value': total_value,
        'unique_cards': unique_cards,
        'completed_sets': completed_sets,
        'rarity_totals': rarity_totals,
        'type_totals': type_totals,
        'user': user,
    })

CollectiDex/portfolio/templates/portfolio/cards_by_rarity.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h2 class="text-center mb-4">Cards of Rarity: {{ rarity }}</h2>

    {% if page_obj %}
        <div class="row">
            {% for user_card in page_obj %}
                <div class="col-lg-2 col-md-3 col-sm-4 col-6 mb-4">
                    <div class="card h-100 shadow-md">
                        <img src="{{ user_card.card.image_url }}" class="card-img-top" alt="{{ user_card.card.name }}">
                        <div class="card-body">
                            <h5 class="card-title">{{ user_card.card.name }}</h5>
                            <p class="card-text">
                                <strong>Quantity:</strong> {{ user_card.quantity }}<br>
                                <strong>Variant:</strong> {{ user_card.variant_type }}<br>
                                <strong>Rarity:</strong> {{ user_card.card.rarity }}<br>
                                <strong>Type:</strong> {{ user_card.card.type }}<br>
                                <strong>Series:</strong> {{ user_card.card.set.series }}<br>
                                <strong>Set:</strong> {{ user_card.card.set.name }}<br>
                                <strong>Card ID:</strong> {{ user_card.card.card_id }}
                            </p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        <!-- Pagination Navigation -->
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}

                {% for page_num in page_obj.paginator.page_range %}
                    <li class="page-item {% if page_obj.number == page_num %}active{% endif %}">
                        <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                    </li>
                {% endfor %}

                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    {% else %}
        <p>No cards found of this type in your collection.</p>
    {% endif %}
</div>
{% endblock %}

CollectiDex/portfolio/templates/portfolio/cards_by_type.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h2 class="text-Center mb-4">Cards of Type: {{ card_type }}</h2>

    {% if page_obj %}
        <div class="row">
            {% for user_card in page_obj %}
                <div class="col-lg-2 col-md-3 col-sm-4 col-6 mb-4">
                    <div class="card h-100 shadow-md">
                        <img src="{{ user_card.card.image_url }}" class="card-img-top" alt="{{ user_card.card.name }}">
                        <div class="card-body">
                            <h5 class="card-title">{{ user_card.card.name }}</h5>
                            <p class="card-text">
                                <strong>Quantity:</strong> {{ user_card.quantity }}<br>
                                <strong>Variant:</strong> {{ user_card.variant_type }}<br>
                                <strong>Rarity:</strong> {{ user_card.card.rarity }}<br>
                                <strong>Type:</strong> {{ user_card.card.type }}<br>
                                <strong>Series:</strong> {{ user_card.card.set.series }}<br>
                                <strong>Set:</strong> {{ user_card.card.set.name }}<br>
                                <strong>Card ID:</strong> {{ user_card.card.card_id }}
                            </p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        <!-- Pagination Navigation -->
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}

                {% for page_num in page_obj.paginator.page_range %}
                    <li class="page-item {% if page_obj.number == page_num %}active{% endif %}">
                        <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                    </li>
                {% endfor %}

                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    {% else %}
        <p>No cards found of this type in your collection.</p>
    {% endif %}
</div>
{% endblock %}

CollectiDex/portfolio/templates/portfolio/dashboard.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-5 mb-5">
        <h2 class="text-center mb-4">Dashboard</h2>
        <div class="row g-4">
            <!-- Total Cards in Collection -->
            <div class="col-lg-3 col-md-6 card-image-top">
                <div class="card text-center shadow-sm">
                    <a href="{% url 'portfolio:collection_cards' %}" class="stretched-link"></a>
                    <div class="card-header bg-primary text-white">
                        Total Cards in Collection
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">{{ total_cards }}</h5>
                        <p class="card-text">Total number of cards in your collection.</p>
                    </div>
                </div>
            </div>

            <!-- Total Value of Collection -->
            <div class="col-lg-3 col-md-6">
                <div class="card text-center shadow-sm card-image-top">
                    <div class="card-header bg-success text-white">
                        Total Value
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">${{ total_value|floatformat:2 }}</h5>
                        <p class="card-text">The current total value of your collection.</p>
                    </div>
                </div>
            </div>

            <!-- Unique Cards -->
            <div class="col-lg-3 col-md-6">
                <div class="card text-center shadow-sm card-image-top">
                    <div class="card-header bg-info text-white">
                        Unique Cards
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">{{ unique_cards }}</h5>
                        <p class="card-text">Number of unique cards in your collection.</p>
                    </div>
                </div>
            </div>

            <!-- Sets Completed -->
            <div class="col-lg-3 col-md-6">
                <div class="card text-center shadow-sm card-image-top">
                    <a href="{% url 'portfolio:collection_sets' %}" class="stretched-link"></a>
                    <div class="card-header bg-warning text-white">
                        Sets Completed
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">{{ completed_sets }}</h5>
                        <p class="card-text">The number of sets you've completed.</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="row g-4 mt-4">
            <div class="col-lg-6">
                <div class="card shadow-sm">
                    <div
                        class="card-header bg-secondary text-white"
                        data-bs-toggle="collapse"
                        data-bs-target="#typeCollapse"
                        aria-expanded="false"
                        aria-controls="typeCollapse"
                        role="button"
                        style="cursor: pointer;">
                        Cards Per Type
                    </div>
                    <div class="collapse" id="typeCollapse">
                        <div class="list-group">
                            {% for type in type_totals %}
                                <a href="{% url 'portfolio:cards_by_type' type.card__supertype %}" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                                    {{ type.card__supertype }} <span class="badge text-bg-secondary">{{ type.total }}</span>
                                </a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-6">
                <div class="card shadow-sm">
                    <div
                        class="card-header bg-secondary text-white"
                        data-bs-toggle="collapse"
                        data-bs-target="#rarityCollapse"
                        aria-expanded="true"
                        aria-controls="rarityCollapse"
                        role="button"
                        style="cursor: pointer;">
                        Cards Per Rarity
                    </div>
                    <div class="collapse show" id="rarityCollapse">
                        <div class="list-group">
                            {% for rarity in rarity_totals %}
                                <a href="{% url 'portfolio:cards_by_rarity' rarity.card__rarity %}" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                                    {{ rarity.card__rarity }} <span class="badge text-bg-secondary">{{ rarity.total }}</span>
                                </a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

CollectiDex/portfolio/templates/portfolio/total_cards_in_collection.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h2 class="text-center mb-4">Total Cards in Collection</h2>
    {% if page_obj %}
        <div class="row">
            {% for user_card in page_obj.object_list %}
                <div class="col-lg-2 col-md-3 col-sm-4 col-6 mb-4">
                    <div class="card h-100 shadow-md">
                        <img src="{{ user_card.card.image_url }}" class="card-img-top" alt="{{ user_card.card.name }}">
                        <div class="card-body">
                            <h5 class="card-title">{{ user_card.card.name }}</h5>
                            <p class="card-text">
                                <strong>Quantity:</strong> {{ user_card.quantity }}<br>
                                <strong>Variant:</strong> {{ user_card.variant_type }}<br>
                                <strong>Rarity:</strong> {{ user_card.card.rarity }}<br>
                                <strong>Type:</strong> {{ user_card.card.type }}<br>
                                <strong>Series:</strong> {{ user_card.card.set.series }}<br>
                                <strong>Set:</strong> {{ user_card.card.set.name }}<br>
                                <strong>Card ID:</strong> {{ user_card.card.card_id }}
                            </p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        <!-- Pagination Navigation -->
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}
                {% for page_num in page_obj.paginator.page_range %}
                    <li class="page-item {% if page_obj.number == page_num %}active{% endif %}">
                        <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                    </li>
                {% endfor %}
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    {% else %}
        <p>No cards found in your collection.</p>
    {% endif %}
</div>
{% endblock %}

CollectiDex/portfolio/templates/portfolio/total_sets_in_collection.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h2 class="text-center mb-4">Total Sets in Collection</h2>
    {% if page_obj %}
        <div class="row">
            {% for item in page_obj %}
                <div class="col-lg-2 col-md-3 col-sm-4 col-6 mb-4">
                    <div class="card h-100 shadow-md">
                    <a href="{% url 'sets:set_view' item.user_set.id %}">
                        <img src="{{ item.user_set.image_url }}" class="card-img-top img-card-custom" alt="{{ item.user_set.name }}">
                    </a>
                        <div class="card-body">
                            <h5 class="card-title">{{ item.user_set.name }}</h5>
                            <p class="card-text">
                                <strong>ID:</strong> {{ item.user_set.id }}<br>
                                <strong>Series:</strong> {{ item.user_set.series }}<br>
                                <strong>Printed Total:</strong> {{ item.user_set.printed_total }}<br>
                                <strong>Total:</strong> {{ item.user_set.total }}<br>
                                <strong>Ptcgo code:</strong> {{ item.user_set.ptcgo_code }}<br>
                                <strong>Completion Progress:</strong> {{ item.user_cards_in_set }}/{{ item.user_set.total }}
                            </p>


                            <!-- Progress Bar -->
                            <div class="progress" role="progressbar" aria-label="Set completion progress"
                                 aria-valuenow="{{ item.completion_percentage }}" aria-valuemin="0" aria-valuemax="100">
                                <div class="progress-bar progress-bar-striped progress-bar-animated overflow-visible text-dark"
                                     style="width: {{ item.completion_percentage }}%">{{ item.completion_percentage|floatformat:0 }}%
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        <!-- Pagination Navigation -->
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}
                {% for page_num in page_obj.paginator.page_range %}
                    <li class="page-item {% if page_obj.number == page_num %}active{% endif %}">
                        <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                    </li>
                {% endfor %}
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    {% else %}
        <p>No cards found in your collection.</p>
    {% endif %}
</div>
{% endblock %}